### ISSUE TITLE
Should encoded query param be decoded?

### ISSUE THREAD

**Issue by aivchen** [thephpleague/uri-src#113]
| Q       | A     |
|---------|-------|
| Package | league/uri-components |
| Version | 2.4.1 |

### Question

Let's imagine we have the following url: `https://example.com?origin=http%3A%2F%2Fanotherexample.com%2F%3Fnestedparam%3D1`

So `origin` query param contains encoded version of `http://anotherexample.com/?nestedparam=1`

And I have this code:
```php
$query = League\Uri\Components\Query::createFromRFC3986('origin=http%3A%2F%2Fanotherexample.com%2F%3Fnestedparam%3D1');
$query = $query->append('onemoreparam=value');

print $query;
```

What I get:
```
origin=http://anotherexample.com/?nestedparam=1&onemoreparam=value
```

What I expect:
```
origin=http%3A%2F%2Fanotherexample.com%2F%3Fnestedparam%3D1&onemoreparam=value
```

Is it correct behavior?

**Comment by nyamsprod** [comment]
@aivchen thanks for using the library. 

Yes it is the expected behaviour because the library does not double encode to avoid bug between multiple encoding/decoding process that may or may not take place. The only exception being `#` which will be encoded because it is the delimiter for the fragment component.

```php
<?php

echo Query::new()->appendTo('url', 'http://exmple.com#top')->getUriComponent(), PHP_EOL;
// display ?url=http://exmple.com%23top
```

_the `Query::new` named constructor is from the upcoming v7 version 😉_
