### ISSUE TITLE
Incorrect encoding of commas in query string

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/uri-src#115]
### Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|-------------|-------------|
| Package     | league/uri  |
| Version     | 7.1.0       |
| PHP version | 8.2.8       |
| OS Platform | Linux       |

#### Summary

Commas are not correctly encoded, in expansion. AWS CloudFront rejects the URLs generated by this package as invalid.

#### Standalone code, or other way to reproduce the problem

```php
$template = new League\Uri\UriTemplate('https://example.com/{?list}');
$uri = $template->expandOrFail(['list' => ['a', 'b']]);
echo $uri->toString();
```

#### Expected result

```
https://example.com/?list=a%2Cb
```

#### Actual result

```
https://example.com/?list=a,b
```

**Comment by nyamsprod** [comment]
@GrahamCampbell thanks for the report. The package follows and successfully passes the [uritemplate-tests](https://github.com/uri-templates/uritemplate-test) independent test suite specifically 

- https://github.com/uri-templates/uritemplate-test/blob/master/extended-tests.json#L32 (see how the geocode variable is expanded)
- https://github.com/uri-templates/uritemplate-test/blob/master/spec-examples.json#L73

If I "fix" to the expected behaviour then my tests will fail the independent tests.
So unless I am misreading the tests, I would say that AWS CloudFront is in the wrong 🤔.

**Comment by GrahamCampbell** [comment]
OK, this is fair. It seems in practice, nobody implements this stuff the same, regardless of what the spec says, lol.
